import { Inter } from 'next/font/google'
import '../globals.css'
import { UserNavigation } from '../../components/UserNavigation.jsx'
import { Footer } from '../../components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className=''>
          <UserNavigation />
        </div>
        <div className=''>
          {children}
        </div>
        <div>
        <Footer />
        </div>
      </body>
    </html>
  )
}
