// import { Inter } from 'next/font/google'
import { Poppins } from "next/font/google";
import "../globals.css";
import { UserNavigation } from "../../components/UserNavigation.jsx";
import { Footer } from "../../components/Footer";

// const inter = Inter({ subsets: ['latin'] })
const poppins = Poppins({
  weight: "400",
  style: "normal",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className="">
          <UserNavigation />
        </div>
        <div className="mt-20">{children}</div>
        <div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
