import { Inter } from 'next/font/google'
import '../globals.css'
import { CompanyNavigation } from '../../components/CompanyNavigation.jsx'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='flex w-full'>
        <div className='w-1/6'>
          <CompanyNavigation />
        </div>
        <div className='w-5/6 lg:w-4/6 md:w-4/6 pt-20'>
          {children}
        </div>
        </div>
        
      </body>
    </html>
  )
}
