import { Poppins } from "next/font/google";
import "../globals.css";
import { CompanyNavigation } from "../../components/CompanyNavigation.jsx";

const poppins = Poppins({ 
  weight: "400", 
  style: "normal", 
  subsets: ["latin"] 
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className="flex w-full">
          <div className="w-1/6">
            <CompanyNavigation />
          </div>
          <div className="w-5/6 pt-20">{children}</div>
        </div>
      </body>
    </html>
  );
}
